import { GoogleGenAI, Type, Schema } from '@google/genai';
import { PBIMProject } from '../pbim/schema';

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

const actionSchema: Schema = {
  type: Type.OBJECT,
  properties: {
    action: { type: Type.STRING },
    target_id: { type: Type.STRING },
    operation: { type: Type.STRING },
    direction: { type: Type.STRING },
    distance_m: { type: Type.NUMBER },
    constraints: {
      type: Type.OBJECT,
      properties: {
        preserve_corridor: { type: Type.BOOLEAN },
        preserve_garage: { type: Type.BOOLEAN },
        minimum_setbacks: { type: Type.BOOLEAN }
      }
    },
    explanation: { type: Type.STRING, description: "Mensagem curta explicando as mudanças para o arquiteto." }
  },
  required: ["action", "target_id", "operation", "explanation"]
};

export async function parseActionPrompt(prompt: string, targetId: string, currentProject: PBIMProject) {
  const systemInstruction = `
Você é o ActionParserAgent do ARQCdR. 
Seu objetivo é ler a intenção arquitetônica (prompt) de contexto para um objeto específico (id) e retornar a Action estruturada (ActionJSON).
Não altere a geometria você mesmo. Retorne como a mudança deve acontecer no espaço, com distâncias e restrições.
Use estritamente o Schema de resposta para que o Engine consiga rodar a transformação determinística.
  `;

  // We feed the current project logic as context
  const context = `
Current Target ID: ${targetId}
Project Name: ${currentProject.name}
  `;

  const response = await ai.models.generateContent({
    model: 'gemini-3.1-pro-preview',
    contents: context + "\\n\\nUser Prompt:\\n" + prompt,
    config: {
      responseMimeType: "application/json",
      responseSchema: actionSchema,
      systemInstruction: systemInstruction,
      temperature: 0.1,
      tools: [{ googleSearch: {} }]
    }
  });

  const text = response.text;
  if (!text) {
    throw new Error("No output generated by ActionParserAgent");
  }

  return JSON.parse(text);
}
